<?php

namespace Booking\AppBundle\Repository;

/**
 * AirportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirportRepository extends \Doctrine\ORM\EntityRepository
{

    public function getWithCodeIcao($icaocode) {
        $qb = $this->createQueryBuilder('e');

        $qb
            ->select('e')
            //->where('e.removed = :rm')
            //->setParameter('rm', false )
            ->andWhere('e.codes.icao = :icaocode')
            ->setParameter('icaocode', $icaocode )
        ;

        return $qb
            ->getQuery()
            ->getOneOrNullResult();
    }
}
