<?php

namespace AppBundle\Repository;

/**
 * AirportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirportRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllVisible() {
        $qb = $this->createQueryBuilder('e');

        $qb
        ->select('e')
        ->where('e.removed = :rm')
        ->setParameter('rm', false );

        return $qb
        ->getQuery()
        ->getResult();
    }
}
