<?php

namespace AppBundle\Repository;

/**
* BookRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLast($size = 20){
        $qb = $this->createQueryBuilder('b');

        return $qb
        ->orderBy('b.id', 'DESC')
        ->getQuery()
        ->setMaxResults($size)
        ->getResult();
    }

    public function getUserLast($user, $size = 10){
        $qb = $this->createQueryBuilder('b');

        $qb
        ->orderBy('b.id', 'DESC')
        ->where('b.user = :user')
        ->setParameter('user', $user);

        return $qb
        ->getQuery()
        ->setMaxResults($size)
        ->getResult();
    }

    public function getOneLast(){
        return $this->createQueryBuilder('e')
        ->orderBy('e.id', 'DESC')
        ->setMaxResults(1)
        ->getQuery()
        ->getOneOrNullResult();
    }
}
