<?php

namespace AppBundle\Repository;

/**
* BookRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class SubBookRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastEdit($parent, $state = "WAITING"){
        $qb = $this->createQueryBuilder('sb');

        $qb->select('sb')
        ->where('sb.parent = :parent')
        ->setParameter('parent', $parent)
        ->andwhere('sb.state = :state')
        ->setParameter('state', $state);

        return $qb
        ->orderBy('sb.id', 'DESC')
        ->getQuery()
        ->getOneOrNullResult();
    }

    public function getChargedCountEdit($parent){
        $qb = $this->createQueryBuilder('sb');

        $qb->select('sb')
        ->where('sb.parent = :parent')
        ->setParameter('parent', $parent)
        ->andwhere('sb.charged = true');

        return $qb
        ->getQuery()
        ->getScalarResult();
    }
}
