<?php

namespace AppBundle\Repository;

/**
* BookRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class SubBookRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastEdit($parent){
        $qb = $this->createQueryBuilder('sb');

        $qb->select('sb')
        ->where('sb.parent = :parent')
        ->setParameter('parent', $parent);

        return $qb
        ->orderBy('b.id', 'DESC')
        ->getQuery()
        ->getOneOrNullResult();
    }
}
