<?php

namespace AppBundle\Repository;

/**
* BookRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllVisible() {
        $qb = $this->createQueryBuilder('u');

        $qb
        ->select('u')
        ->where('NOT u.roles LIKE :role')
        ->setParameter('role', '%"ROLE_SUPER_ADMIN"%' )
        ->andwhere('u.removed = :rm')
        ->setParameter('rm', false );

        return $qb
        ->getQuery()
        ->getResult();
    }

    public function getWaiting() {
        $qb = $this->createQueryBuilder('u');

        $qb
        ->select('u')
        ->where('u.enabled = :arg')
        ->andwhere('u.removed = :arg')
        ->setParameter('arg', false );

        return $qb
        ->getQuery()
        ->getResult();
    }

}
