imports:
    - { resource: parameters.php }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    upload_directory: '%kernel.root_dir%/../web/uploads'

    jwt_private_key_path: '%kernel.root_dir%/../var/jwt/private.pem' # ssh private key path
    jwt_public_key_path:  '%kernel.root_dir%/../var/jwt/public.pem'  # ssh public key path
    jwt_key_pass_phrase:  'unicbooking'                              # ssh key pass phrase
    jwt_token_ttl:        null

framework:
    #esi:             ~
    translator:      { fallbacks: ["fr", "%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        #url: "%database_url%"
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    encryption: "%mailer_encryption%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOSUserBundle Configuration
fos_user:
    db_driver: orm # 'mongodb' or 'couchdb'
    firewall_name: main
    user_class: Booking\UserBundle\Entity\User
    registration:
        form:
            type: Booking\UserBundle\Form\RegistrationType
    from_email:
        address: you@example.com
        sender_name: You

fqtdb_core_manager:
    methods:
        service: 'booking.user.manager.user'
        content:
            createUser:
                method: 'createUser'
                environment: 'global'
                fullName: 'Create'
            disableUser:
                method: 'disableUser'
                environment: 'object'
                fullName: 'Disable/Enable'
            editUser:
                method: 'editUser'
                environment: 'object'
                fullName: 'Edit'
    entities:
        airport:
            access: ROLE_ADMIN
            title: Airport
            fullName: Booking\AppBundle:Airport
            methods: [ list, add, edit ]
        product:
            access: ROLE_ADMIN
            title: Product
            fullName: Booking\AppBundle:Product
            methods: [ list, add, edit, remove ]
        client:
            access: ROLE_ADMIN
            title: Client
            fullName: Booking\AppBundle:Client
            methods: [ list, add, edit, remove ]
        car:
            access: ROLE_ADMIN
            title: Car
            fullName: Booking\AppBundle:Car
            methods: [ list, add, edit, remove ]
        location:
            access: ROLE_ADMIN
            title: Location
            fullName: Booking\AppBundle:Location
            methods: [ list, add, edit, remove ]
        service:
            access: ROLE_ADMIN
            title: Service
            fullName: Booking\AppBundle:Service
            methods: [ list, add, edit, remove ]
        user:
            access: ROLE_ADMIN
            title: User
            fullName: Booking\UserBundle:User
            methods: [ list, createUser, editUser, disableUser ]
            formType: RegistrationType

db_manager:
    templates:
        #index_view: ...
        main: dashboard/table/entity.html.twig
    views:
        - { action: list, custom_view: dashboard/table/list.html.twig, container: [ ] }
        - { action: edit, custom_view: dashboard/table/form.html.twig, container: [ ] }
        - { action: add, custom_view: dashboard/table/form.html.twig, container: [ ] }
        - { action: createUser, custom_view: dashboard/table/form.html.twig, container: [ ] }
        - { action: editUser, custom_view: dashboard/table/form.html.twig, container: [ ] }
    links:
        - { action: createUser, container: [ list ] }
        - { action: editUser, container: [ list ] }
        - { action: edit, container: [ list ] }
        - { action: add, container: [ list ] }
        - { action: list, container: [ add, createUser ] }

fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }

lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'
