booking_api:
    resource: "@BookingApiBundle/Controller/"
    type:     rest
    prefix:   /api

booking_app:
    resource: "@BookingAppBundle/Controller/"
    type:     annotation
    prefix:   /

booking_user:
    resource: "@BookingUserBundle/Controller/"
    type:     annotation
    prefix:   /user

db.manager:
    resource: "@DBManagerBundle/Resources/config/routing.yml"
    prefix:   /database

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /hold

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/login_check