# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.checker.book:
        class: AppBundle\Checker\BookManager
        arguments: [ "@doctrine.orm.entity_manager", "@security.authorization_checker", "@security.token_storage" ]
    exception.listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: [ "@twig" ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    app.book.form:
        class: AppBundle\Form\BookType
        arguments: [ "@security.token_storage" ]
        tags: [{ name: form.type }]
    app.mailer:
        class: AppBundle\Mailer\SenderManager
        arguments: [ "@mailer", "@templating" ]
