<?php

namespace Booking\AppBundle\Repository\Metadata;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLast(){
        $qb = $this->createQueryBuilder('b');

        $qb->select('b')
            ->andwhere('b.date >= :limit_top')
            ->setParameter('limit_top', new \DateTime())
            ->andwhere('b.date <= :limit_bottom')
            ->setParameter('limit_bottom', new \DateTime("+1 month"))
            ->orderBy('b.date', 'ASC');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
