services:
#    booking_app.example:
#        class: Booking\AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    app.db.manager.listener:
        class: Booking\AppBundle\Subscriber\DatabaseManagerSubscriber
        tags:
            - { name: kernel.event_subscriber }


#    booking.app.form.data_transformer.flight:
#        class: Booking\AppBundle\Form\DataTransformer\CodeToFlightTransformer
#        arguments: ["@doctrine.orm.entity_manager"]

#    booking.app.form.flight:
#        class: Booking\AppBundle\Form\Core\FlightType
#        arguments: ["@booking.app.form.data_transformer.flight"]
#        tags:
#            - { name: form.type }
