services:

    booking.user.manager.user:
        class: Booking\UserBundle\Manager\UserManager
        arguments: ["@service_container"]

    booking.user.subscriber:
        class: Booking\UserBundle\Events\UserSubscriber
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_subscriber, connection: default }
